Repository PKkDev/CenterEcoTech, pull requests merged in 2022-12, with the labels that each got.

#47 add measurement
  CenterEcoTech.API/Controllers/MeasurementController.cs
  CenterEcoTech.Domain/Query/MeasurementRequest/AddMeasurementQuery.cs
  CenterEcoTech.Domain/ServicesContract/IMeasurementService.cs
  CenterEcoTech.Infrastructure/Services/MeasurementService.cs
Labels: backend

#49 38 processing indications working with meters
  CenterEcoTech.API/Controllers/MeasurementController.cs
  CenterEcoTech.Domain/DTO/MeasurementRequest/LastCounterDto.cs
  CenterEcoTech.Domain/Query/MeasurementRequest/AddCounterQuery.cs
  CenterEcoTech.Domain/Query/MeasurementRequest/AddMeasurementRequestQuery.cs
  CenterEcoTech.Domain/ServicesContract/IMeasurementService.cs
  CenterEcoTech.EfData/Context/AppDataBaseContext.cs
  CenterEcoTech.EfData/Entities/Client.cs
  CenterEcoTech.EfData/Entities/Counter.cs
  CenterEcoTech.EfData/Entities/Measurement.cs
  CenterEcoTech.EfData/Migrations/20221217172144_Initial.Designer.cs
  CenterEcoTech.EfData/Migrations/20221219184031_update1.Designer.cs
  CenterEcoTech.EfData/Migrations/20221219184031_update1.cs
  CenterEcoTech.EfData/Migrations/20221219185151_update2.cs
  CenterEcoTech.EfData/Migrations/20221220084326_initial.Designer.cs
  CenterEcoTech.EfData/Migrations/20221220084326_initial.cs
  CenterEcoTech.EfData/Migrations/AppDataBaseContextModelSnapshot.cs
  CenterEcoTech.Infrastructure/Services/MeasurementService.cs
Labels: backend

#50 48 fix process measurement
  CenterEcoTech.Infrastructure/Services/MeasurementService.cs
Labels: backend

#52 19 registration form
  center-eco-tech-client/src/app/modules/authorize/authorize-routing.module.ts
  center-eco-tech-client/src/app/modules/authorize/authorize.module.ts
  center-eco-tech-client/src/app/modules/authorize/log-in-page/log-in-page.component.html
  center-eco-tech-client/src/app/modules/authorize/reg-page/domain.ts
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.html
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.scss
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.spec.ts
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.ts
Labels: frontend

#55 add banner component and update empty pages
  center-eco-tech-client/src/app/modules/client-app/client-app.module.ts
  center-eco-tech-client/src/app/modules/client-app/pages/accruals-page/accruals-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/news-page/news-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/services-page/services-page.component.html
  center-eco-tech-client/src/app/modules/shared/empty-banner/empty-banner.component.html
  center-eco-tech-client/src/app/modules/shared/empty-banner/empty-banner.component.scss
  center-eco-tech-client/src/app/modules/shared/empty-banner/empty-banner.component.spec.ts
  center-eco-tech-client/src/app/modules/shared/empty-banner/empty-banner.component.ts
  center-eco-tech-client/src/app/modules/shared/shared.module.ts
Labels: frontend

#56 add history page and table to page
  center-eco-tech-client/src/app/modules/client-app/client-app-routing.module.ts
  center-eco-tech-client/src/app/modules/client-app/client-app.module.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/domain.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-type-converter.pipe.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-type-converter.pipe.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.ts
Labels: feature, frontend

#59 adding links and checkbox policy
  center-eco-tech-client/src/app/modules/authorize/log-in-page/log-in-page.component.html
  center-eco-tech-client/src/app/modules/authorize/log-in-page/log-in-page.component.scss
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.html
  center-eco-tech-client/src/app/modules/authorize/reg-page/registration.component.scss
  center-eco-tech-client/src/assets/img/app-store.png
  center-eco-tech-client/src/assets/img/google-play.png
Labels: frontend

#58 33 adding indication-page
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/domain.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication-type-converter.pipe.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication-type-converter.pipe.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.ts
Labels: feature, frontend

#60 37 indications page meters
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/domain.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.ts
  center-eco-tech-client/src/assets/img/cold-water.svg
  center-eco-tech-client/src/assets/img/gas.svg
  center-eco-tech-client/src/assets/img/hot-water.svg
  center-eco-tech-client/src/assets/meters.json
Labels: frontend

#61 54 check relation for task
  CenterEcoTech.API/Controllers/MeasurementController.cs
  CenterEcoTech.Domain/DTO/MeasurementRequest/LastCounterDto.cs
  CenterEcoTech.Domain/DTO/MeasurementRequest/MeasurementRequestDto.cs
  CenterEcoTech.Domain/Query/MeasurementRequest/AddCounterQuery.cs
  CenterEcoTech.Domain/Query/MeasurementRequest/GetMeasurementHistoryQuery.cs
  CenterEcoTech.Infrastructure/Services/MeasurementService.cs
  center-eco-tech-client/src/app/modules/authorize/log-in-page/log-in-page.component.html
  center-eco-tech-client/src/app/modules/authorize/log-in-page/log-in-page.component.scss
  center-eco-tech-client/src/app/modules/client-app/client-app.module.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/domain.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indication/indication.component.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/domain.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-history.component.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-type-converter.pipe.spec.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-history/indications-type-converter.pipe.ts
  center-eco-tech-client/src/app/modules/client-app/pages/indications-page/indications-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/news-page/news-page.component.html
  center-eco-tech-client/src/app/modules/client-app/pages/news-page/news-page.component.scss
  center-eco-tech-client/src/app/modules/client-app/pages/news-page/news-page.component.ts
  center-eco-tech-client/src/assets/articles/articles.json
  center-eco-tech-client/src/assets/meters.json
Labels: backend, frontend
